apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wmw.fullname" . }}-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: mgk.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "wmw.fullname" . }}-wave
                port:
                  number: 80
