apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "wmw.fullname" . }}-pv-wave5
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.wave.pv.wave5 }}
