apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wmw.fullname" . }}-pvc-wave5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
  volumeMode: Filesystem
  volumeName: {{ include "wmw.fullname" . }}-pv-wave5



